'use client';import{useEffect,useState}from'react';import{supabase}from'../../../lib/supabase';
export default function MAM(){const[M,setM]=useState([]),[mid,setMid]=useState(''),[U,setU]=useState([]),[T,setT]=useState([]),[P,setP]=useState([]),[sel,setSel]=useState(null),[msg,setMsg]=useState('');
async function api(b){let s=supabase(),{data:{session}}=await s.auth.getSession(),r=await fetch(process.env.NEXT_PUBLIC_SUPABASE_URL+'/functions/v1/mam-engine',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify(b)}),d=await r.json();if(!r.ok)throw Error(d.error);return d}
async function load(){let s=supabase(),{data:{user}}=await s.auth.getUser();if(!user)return location='/login';let{data:p}=await s.from('profiles').select('role').eq('id',user.id).single();if(p?.role!=='admin')return location='/customer';let{data:m}=await s.from('mams').select('*').order('created_at',{ascending:false});let{data:u}=await s.from('profiles').select('id,full_name').eq('role','customer');setM(m||[]);setU(u||[]);if(!mid&&m?.[0])setMid(String(m[0].id))}
async function loadTrades(){if(!mid)return;let{data}=await supabase().from('mam_master_trades').select('*').eq('mam_id',mid).order('open_time',{ascending:false});setT(data||[])}
useEffect(()=>{load()},[]);useEffect(()=>{loadTrades()},[mid]);
async function newMam(e){e.preventDefault();let f=new FormData(e.currentTarget);try{await api({action:'create_mam',name:f.get('name'),currency:'USD',allocation_method:f.get('method'),performance_fee_pct:+f.get('fee')||0});setMsg('MAM created');load()}catch(e){setMsg(e.message)}}
async function member(e){e.preventDefault();let f=new FormData(e.currentTarget);try{await api({action:'add_member',mam_id:+mid,account_id:f.get('user'),allocation_weight:+f.get('weight')||1,allocation_percentage:f.get('pct')?+f.get('pct'):null,risk_multiplier:+f.get('risk')||1,minimum_equity:+f.get('min')||0});setMsg('Member saved')}catch(e){setMsg(e.message)}}
async function trade(e){e.preventDefault();let f=new FormData(e.currentTarget),b={action:'create_trade',mam_id:+mid,symbol:f.get('symbol'),side:f.get('side'),open_price:+f.get('open'),open_time:new Date(f.get('ot')).toISOString(),trade_source:f.get('source'),currency:'USD',save_draft:false};if(f.get('ct')){b.close_time=new Date(f.get('ct')).toISOString();b.close_price=+f.get('close');b.result_mode=f.get('mode');if(b.result_mode==='PERCENTAGE_RETURN')b.result_percentage=+f.get('result');if(b.result_mode==='MASTER_PL_PROPORTIONAL')b.master_profit_loss=+f.get('result');if(b.result_mode==='FIXED_DISTRIBUTION')b.fixed_distribution_amount=+f.get('result')}try{let d=await api(b);setSel(d.trade);setMsg('Trade created; participant equity frozen');loadTrades()}catch(e){setMsg(e.message)}}
async function close(e){e.preventDefault();let f=new FormData(e.currentTarget),b={action:'close_trade',trade_id:sel.id,close_price:+f.get('close'),close_time:new Date(f.get('ct')).toISOString(),result_mode:f.get('mode')};if(b.result_mode==='PERCENTAGE_RETURN')b.result_percentage=+f.get('result');if(b.result_mode==='MASTER_PL_PROPORTIONAL')b.master_profit_loss=+f.get('result');if(b.result_mode==='FIXED_DISTRIBUTION')b.fixed_distribution_amount=+f.get('result');try{let d=await api(b);setSel(d.trade);setMsg('Closed. Preview before distribution.');loadTrades()}catch(e){setMsg(e.message)}}
async function preview(t=sel){try{let d=await api({action:'preview',trade_id:t.id});setSel(t);setP(d.items||[]);setMsg('Preview only — balances unchanged')}catch(e){setMsg(e.message)}}
async function dist(){if(!confirm('CONFIRM distribution? This posts ledger entries and balances atomically.'))return;try{let d=await api({action:'distribute',trade_id:sel.id,idempotency_key:crypto.randomUUID()});setMsg('Distributed to '+d.count+' accounts. Net '+d.net);setP([]);loadTrades()}catch(e){setMsg(e.message)}}
async function reverse(){let reason=prompt('Reversal reason');if(!reason)return;let s=supabase(),{data,error}=await s.rpc('mam_reverse_distribution',{p_trade_id:sel.id,p_reason:reason,p_request_id:crypto.randomUUID()});setMsg(error?error.message:'Reversed '+JSON.stringify(data));loadTrades()}
async function correct(){let reason=prompt('Correction reason'),v=prompt('Correct result value');if(!reason||v===null)return;let a={p_trade_id:sel.id,p_result_percentage:null,p_master_pl:null,p_fixed_amount:null,p_reason:reason,p_request_id:crypto.randomUUID()};if(sel.result_mode==='PERCENTAGE_RETURN')a.p_result_percentage=+v;if(sel.result_mode==='MASTER_PL_PROPORTIONAL')a.p_master_pl=+v;if(sel.result_mode==='FIXED_DISTRIBUTION')a.p_fixed_amount=+v;let{data,error}=await supabase().rpc('mam_correct_distribution',a);setMsg(error?error.message:'Correction '+JSON.stringify(data));loadTrades()}
return <main><nav><b>TRYOUR<span>TRADES</span> · MAM</b><a href="/admin">Company</a></nav><section><h1>MAM Allocation Engine</h1><p className="notice">{msg}</p><div className="grid"><div className="card"><h3>Create MAM</h3><form onSubmit={newMam}><input name="name" placeholder="MAM name" required/><select name="method"><option>PROPORTIONAL_BY_EQUITY</option><option>FIXED_PERCENTAGE</option><option>FIXED_WEIGHT</option><option>CUSTOM_MULTIPLIER</option></select><input name="fee" type="number" step=".01" placeholder="Performance fee %"/><button className="primary">CREATE</button></form></div><div className="card"><h3>Select MAM</h3><select value={mid} onChange={e=>setMid(e.target.value)}><option value="">Select</option>{M.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div></div>
{mid&&<><div className="card"><h3>Add / Update Member</h3><form className="row" onSubmit={member}><select name="user" required><option value="">Customer</option>{U.map(x=><option value={x.id} key={x.id}>{x.full_name||x.id}</option>)}</select><input name="weight" type="number" step=".01" defaultValue="1" placeholder="Weight"/><input name="pct" type="number" step=".01" placeholder="Fixed %"/><input name="risk" type="number" step=".01" defaultValue="1" placeholder="Risk multiplier"/><input name="min" type="number" step=".01" defaultValue="0" placeholder="Min equity"/><button>ADD MEMBER</button></form></div>
<div className="card"><h3>Add Trade / Historical Trade</h3><form className="formgrid" onSubmit={trade}><input name="symbol" placeholder="XAUUSD" required/><select name="side"><option>BUY</option><option>SELL</option></select><input name="ot" type="datetime-local" required/><input name="open" type="number" step="any" placeholder="Open price" required/><input name="ct" type="datetime-local"/><input name="close" type="number" step="any" placeholder="Close price"/><select name="source"><option>MANUAL</option><option>EXTERNAL</option><option>IMPORTED</option><option>SYNTHETIC</option><option>LIVE</option></select><select name="mode"><option>PERCENTAGE_RETURN</option><option>MASTER_PL_PROPORTIONAL</option><option>FIXED_DISTRIBUTION</option></select><input name="result" type="number" step=".0001" placeholder="Return % / Master P&L / Fixed total"/><button className="primary">CREATE & FREEZE SNAPSHOT</button></form></div>
<div className="card tablewrap"><h3>Master Trades</h3><table><thead><tr><th>Ticket</th><th>Symbol</th><th>Side</th><th>Source</th><th>Open</th><th>Close</th><th>Status</th><th></th></tr></thead><tbody>{T.map(t=><tr key={t.id}><td>{t.ticket||t.id}</td><td>{t.symbol}</td><td>{t.side}</td><td>{t.trade_source}</td><td>{t.open_price}</td><td>{t.close_price??'-'}</td><td>{t.trade_status}</td><td><button onClick={()=>{setSel(t);setP([])}}>OPEN</button></td></tr>)}</tbody></table></div>
{sel&&<div className="card"><h2>{sel.ticket} · {sel.symbol} · {sel.side}</h2>{sel.trade_status==='OPEN'&&<form className="row" onSubmit={close}><input name="ct" type="datetime-local" required/><input name="close" type="number" step="any" placeholder="Close price" required/><select name="mode"><option>PERCENTAGE_RETURN</option><option>MASTER_PL_PROPORTIONAL</option><option>FIXED_DISTRIBUTION</option></select><input name="result" type="number" step=".0001" placeholder="Result" required/><button className="primary">CLOSE TRADE</button></form>}<button onClick={()=>preview(sel)}>PREVIEW ALLOCATION</button>{['ALLOCATED','CORRECTED'].includes(sel.trade_status)&&<><button onClick={correct}>CREATE CORRECTION</button><button onClick={reverse}>REVERSE</button></>}</div>}
{P.length>0&&<div className="card tablewrap"><h2>Allocation Preview — no balances changed</h2><table><thead><tr><th>Account</th><th>Snapshot</th><th>%</th><th>Gross</th><th>Fee</th><th>Net</th><th>Before</th><th>After</th></tr></thead><tbody>{P.map(x=><tr key={x.account_id}><td>{x.account_id.slice(0,8)}</td><td>{x.snapshot_equity}</td><td>{x.allocation_pct}</td><td>{x.gross_pl}</td><td>{x.fee}</td><td className={+x.net_pl>=0?'pos':'neg'}>{x.net_pl}</td><td>{x.balance_before}</td><td>{x.balance_after}</td></tr>)}</tbody></table><button onClick={()=>setP([])}>BACK</button><button className="primary" onClick={dist}>CONFIRM & DISTRIBUTE</button></div>}</>}</section></main>}